//! Cross-language parity: replay the golden corpus generated by the Python
//! reference implementation and require byte-identical behavior.

use serde::Deserialize;
use std::collections::HashMap;

use dhad_core::{normalize, sentence_spans, tokenize, tokenize_all, NormalizationMode};

#[derive(Deserialize)]
struct Record {
    input: String,
    normalize: HashMap<String, String>,
    sentences: Vec<(String, usize, usize, String)>,
    tokens: Vec<(String, usize, usize, String)>,
    content_tokens: Vec<(String, usize, usize, String)>,
}

fn records() -> Vec<Record> {
    let raw = include_str!("data/text_golden.jsonl");
    raw.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).expect("golden line must parse"))
        .collect()
}

const MODES: [(&str, NormalizationMode); 4] = [
    ("strict", NormalizationMode::Strict),
    ("lookup", NormalizationMode::Lookup),
    ("search", NormalizationMode::Search),
    ("aggressive", NormalizationMode::Aggressive),
];

#[test]
fn normalize_matches_python_reference() {
    for record in records() {
        for (name, mode) in MODES {
            let expected = &record.normalize[name];
            let actual = normalize(&record.input, mode);
            assert_eq!(
                &actual, expected,
                "normalize({name}) diverged for input: {:?}",
                record.input
            );
        }
    }
}

#[test]
fn sentence_spans_match_python_reference() {
    for record in records() {
        let actual: Vec<(String, usize, usize, String)> = sentence_spans(&record.input)
            .into_iter()
            .map(|s| (s.text, s.start, s.end, s.terminator))
            .collect();
        assert_eq!(
            actual, record.sentences,
            "sentence_spans diverged for input: {:?}",
            record.input
        );
    }
}

#[test]
fn lossless_token_stream_matches_python_reference() {
    for record in records() {
        let actual: Vec<(String, usize, usize, String)> = tokenize_all(&record.input)
            .into_iter()
            .map(|t| (t.text, t.start, t.end, t.kind.as_str().to_string()))
            .collect();
        assert_eq!(
            actual, record.tokens,
            "tokenize_all diverged for input: {:?}",
            record.input
        );
    }
}

#[test]
fn content_tokens_match_python_reference() {
    for record in records() {
        let actual: Vec<(String, usize, usize, String)> = tokenize(&record.input)
            .into_iter()
            .map(|t| (t.text, t.start, t.end, t.kind.as_str().to_string()))
            .collect();
        assert_eq!(
            actual, record.content_tokens,
            "tokenize diverged for input: {:?}",
            record.input
        );
    }
}

#[test]
fn lossless_stream_reconstructs_input() {
    for record in records() {
        let rebuilt: String = tokenize_all(&record.input)
            .into_iter()
            .map(|t| t.text)
            .collect();
        assert_eq!(
            rebuilt, record.input,
            "lossless stream must concatenate back"
        );
    }
}
