//! Port of `dhad.text` — normalization, tokenization, and sentence
//! segmentation with char-accurate source offsets.
//!
//! The Python module is the reference implementation. Every behavioral
//! detail here (alternation order, URL trailing-punctuation splitting,
//! abbreviation guards, closer consumption) exists to match it exactly;
//! `tests/golden.rs` enforces parity against a corpus generated by
//! `tools/generate_rust_golden.py`.

use std::sync::OnceLock;

use regex::Regex;
use unicode_normalization::UnicodeNormalization;

pub use crate::types::{Sentence, Token, TokenKind};

// ── Character classes (mirrors dhad/text.py) ────────────────────────────────

const AR_EXT_LETTER: &str = "چگپژڤ";

/// True for the letters covered by Python's `AR_LETTER` class:
/// `ء-غ ف-ي ٱ ٮ-ۓ ۺ-ۼ ۿ` plus the extension letters.
fn is_arabic_letter(c: char) -> bool {
    matches!(c,
        '\u{0621}'..='\u{063A}' // ء-غ
        | '\u{0641}'..='\u{064A}' // ف-ي
        | '\u{0671}' // ٱ
        | '\u{066E}'..='\u{06D3}' // ٮ-ۓ
        | '\u{06FA}'..='\u{06FC}' // ۺ-ۼ
        | '\u{06FF}' // ۿ
    ) || AR_EXT_LETTER.contains(c)
}

/// True for Python's `AR_DIACRITIC` class. Exact code-point ranges (verified
/// against the reference: `[hex(ord(c)) for c in AR_DIACRITIC]`):
/// 064B–065F, 0670, 06D6–06DC, 06DF–06E8, 06EA–06ED. The Arabic-Indic
/// digits (0660–0669) and ۩ (06E9) are deliberately *not* diacritics.
fn is_arabic_diacritic(c: char) -> bool {
    matches!(c,
        '\u{064B}'..='\u{065F}'
        | '\u{0670}'
        | '\u{06D6}'..='\u{06DC}'
        | '\u{06DF}'..='\u{06E8}'
        | '\u{06EA}'..='\u{06ED}'
    )
}

pub const TATWEEL: char = '\u{0640}';

fn is_arabic_word_char(c: char) -> bool {
    is_arabic_letter(c) || is_arabic_diacritic(c) || c == TATWEEL
}

/// Public boundary predicate for the rule scanner (`B_LEFT`/`B_RIGHT`).
pub fn is_arabic_word_char_pub(c: char) -> bool {
    is_arabic_word_char(c)
}

// ── Normalization ───────────────────────────────────────────────────────────

/// Normalization policies, identical to `dhad.text.NormalizationMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NormalizationMode {
    /// Unicode NFC only.
    Strict,
    /// NFC + strip tashkeel and tatweel (the engine default).
    Lookup,
    /// Lookup + fold hamza/alef/yaa/taa-marbuta variants.
    Search,
    /// Search + drop non-word punctuation and collapse whitespace.
    Aggressive,
}

fn fold_search(c: char) -> char {
    match c {
        'أ' | 'إ' | 'آ' | 'ٱ' => 'ا',
        'ى' => 'ي',
        'ؤ' => 'و',
        'ئ' => 'ي',
        'ة' => 'ه',
        other => other,
    }
}

/// Python `\w` for the AGGRESSIVE stage: letters, digits/numerics, or `_`.
fn is_word_char(c: char) -> bool {
    c == '_' || c.is_alphanumeric()
}

pub fn strip_diacritics(value: &str) -> String {
    let mut output = String::with_capacity(value.len());
    output.extend(value.chars().filter(|c| !is_arabic_diacritic(*c)));
    output
}

pub fn strip_tatweel(value: &str) -> String {
    let mut output = String::with_capacity(value.len());
    output.extend(value.chars().filter(|c| *c != TATWEEL));
    output
}

/// Normalize text according to an explicit policy; see the Python reference.
pub fn normalize(value: &str, mode: NormalizationMode) -> String {
    let result: String = value.nfc().collect();
    if mode == NormalizationMode::Strict {
        return result;
    }
    let mut lookup = String::with_capacity(result.len());
    lookup.extend(
        result
            .chars()
            .filter(|c| !is_arabic_diacritic(*c) && *c != TATWEEL),
    );
    if mode == NormalizationMode::Lookup {
        return lookup;
    }
    let mut search = String::with_capacity(lookup.len());
    search.extend(lookup.chars().map(fold_search));
    if mode == NormalizationMode::Search {
        return search;
    }

    // Collapse punctuation and whitespace in one pass. This avoids both the
    // temporary mapped String and the Vec<&str> previously created by
    // split_whitespace().collect(), while preserving Python parity.
    let mut aggressive = String::with_capacity(search.len());
    let mut pending_space = false;
    for c in search.chars() {
        if is_word_char(c) {
            if pending_space && !aggressive.is_empty() {
                aggressive.push(' ');
            }
            aggressive.push(c);
            pending_space = false;
        } else {
            pending_space = !aggressive.is_empty();
        }
    }
    aggressive
}

// ── Tokenization ────────────────────────────────────────────────────────────

fn char_class(chars: &[(char, char)]) -> String {
    chars
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                format!("\\u{{{:04X}}}", *lo as u32)
            } else {
                format!("\\u{{{:04X}}}-\\u{{{:04X}}}", *lo as u32, *hi as u32)
            }
        })
        .collect()
}

fn token_regex() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| {
        let letter = format!(
            "{}{}",
            char_class(&[
                ('\u{0621}', '\u{063A}'),
                ('\u{0641}', '\u{064A}'),
                ('\u{0671}', '\u{0671}'),
                ('\u{066E}', '\u{06D3}'),
                ('\u{06FA}', '\u{06FC}'),
                ('\u{06FF}', '\u{06FF}'),
            ]),
            AR_EXT_LETTER
        );
        let diacritic = char_class(&[
            ('\u{064B}', '\u{065F}'),
            ('\u{0670}', '\u{0670}'),
            ('\u{06D6}', '\u{06DC}'),
            ('\u{06DF}', '\u{06E8}'),
            ('\u{06EA}', '\u{06ED}'),
        ]);
        let word_char = format!("{letter}{diacritic}\u{0640}");
        let arabic = format!("[{letter}](?:[{word_char}]*[{letter}{diacritic}])?");
        let latin = "[A-Za-zÀ-ÖØ-öø-ÿ]+(?:['’\\-][A-Za-zÀ-ÖØ-öø-ÿ]+)*";
        let number = "[+\\-]?[0-9٠-٩]+(?:[.,٫٬][0-9٠-٩]+)*(?:[%٪])?";
        let url = "(?:https?://|ftp://|www\\.)[^\\s<>\\[\\]{}\"'`]+";
        let email = "[A-Za-z0-9.!#$%&'*+/=?^_`{|}~\\-]+@[A-Za-z0-9\\-]+(?:\\.[A-Za-z0-9\\-]+)+";
        let fenced = "```[\\s\\S]*?```";
        let inline = "`[^`\\n]+`";
        let hashtag = format!("#[{letter}A-Za-z0-9_]+");
        let mention = format!("@[{letter}A-Za-z0-9_]+");
        let pattern = format!(
            "(?P<code>{fenced}|{inline})|(?P<url>{url})|(?P<email>{email})|(?P<hashtag>{hashtag})|(?P<mention>{mention})|(?P<arabic>{arabic})|(?P<number>{number})|(?P<latin>{latin})|(?P<whitespace>\\s+)|(?P<punctuation>[،؛؟.!?,;:…]+)|(?P<symbol>\\S)"
        );
        Regex::new(&pattern).expect("token pattern must compile")
    })
}

const GROUPS: [(&str, TokenKind); 11] = [
    ("code", TokenKind::Code),
    ("url", TokenKind::Url),
    ("email", TokenKind::Email),
    ("hashtag", TokenKind::Hashtag),
    ("mention", TokenKind::Mention),
    ("arabic", TokenKind::ArabicWord),
    ("number", TokenKind::Number),
    ("latin", TokenKind::LatinWord),
    ("whitespace", TokenKind::Whitespace),
    ("punctuation", TokenKind::Punctuation),
    ("symbol", TokenKind::Symbol),
];

const URL_TRAILERS: [char; 6] = ['.', ',', '،', '؛', '؟', '!'];

/// Lossless token stream (whitespace and punctuation included), with char
/// offsets identical to `dhad.text.tokenize(include_non_words=True)`.
pub fn tokenize_all(text: &str) -> Vec<Token> {
    // Regex captures are monotonically ordered. Track the previous boundary
    // instead of allocating a byte-sized lookup table for every document.
    let mut previous_byte = 0usize;
    let mut previous_char = 0usize;
    let mut out = Vec::new();
    for capture in token_regex().captures_iter(text) {
        let (raw, kind) = GROUPS
            .iter()
            .find_map(|(name, kind)| capture.name(name).map(|m| (m, *kind)))
            .expect("alternation always names its match");
        let matched = raw.as_str();
        let start_char = previous_char + text[previous_byte..raw.start()].chars().count();
        let end_char = start_char + matched.chars().count();
        previous_byte = raw.end();
        previous_char = end_char;
        if kind == TokenKind::Url {
            let core = matched.trim_end_matches(&URL_TRAILERS[..]);
            if !core.is_empty() && core.len() != matched.len() {
                let core_chars = core.chars().count();
                out.push(Token {
                    text: core.to_string(),
                    start: start_char,
                    end: start_char + core_chars,
                    kind: TokenKind::Url,
                });
                for (offset, trailer) in matched[core.len()..].chars().enumerate() {
                    let position = start_char + core_chars + offset;
                    out.push(Token {
                        text: trailer.to_string(),
                        start: position,
                        end: position + 1,
                        kind: TokenKind::Punctuation,
                    });
                }
                continue;
            }
        }
        out.push(Token {
            text: matched.to_string(),
            start: start_char,
            end: end_char,
            kind,
        });
    }
    out
}

/// Semantic content tokens only, matching `dhad.text.tokenize()` defaults.
pub fn tokenize(text: &str) -> Vec<Token> {
    tokenize_all(text)
        .into_iter()
        .filter(|token| {
            !matches!(
                token.kind,
                TokenKind::Whitespace | TokenKind::Punctuation | TokenKind::Symbol
            )
        })
        .collect()
}

// ── Sentence segmentation ───────────────────────────────────────────────────

const TERMINATORS: [char; 6] = ['.', '!', '?', '؟', '؛', '…'];
const CLOSERS: [char; 8] = ['"', '\'', '»', '”', '’', ')', ']', '}'];
/// Kept in sync with `dhad/text.py::_ABBREVIATIONS`; the golden corpus
/// guards against silent drift between the two lists.
const ABBREVIATIONS: [&str; 16] = [
    "د.", "أ.د.", "م.", "أ.", "ص.", "ج.", "هـ.", "ق.م.", "م.م.", "Dr.", "Mr.", "Mrs.", "Ms.",
    "Prof.", "e.g.", "i.e.",
];

fn is_ascii_or_arabic_digit(c: char) -> bool {
    c.is_ascii_digit() || ('\u{0660}'..='\u{0669}').contains(&c)
}

fn looks_like_decimal(chars: &[char], index: usize) -> bool {
    index > 0
        && index + 1 < chars.len()
        && is_ascii_or_arabic_digit(chars[index - 1])
        && is_ascii_or_arabic_digit(chars[index + 1])
}

fn looks_like_list_marker(
    chars: &[char],
    dot_index: usize,
    line_content_start: Option<usize>,
) -> bool {
    let Some(head) = line_content_start else {
        return false;
    };
    let mut tail = dot_index;
    while tail > head && chars[tail - 1].is_whitespace() {
        tail -= 1;
    }
    let trimmed = &chars[head..tail];
    // fullmatch `(?:[0-9٠-٩]{1,3}|[A-Za-z]|[أ-ي])`
    match trimmed.len() {
        1 => {
            let c = trimmed[0];
            is_ascii_or_arabic_digit(c)
                || c.is_ascii_alphabetic()
                || ('\u{0623}'..='\u{064A}').contains(&c)
        }
        2 | 3 => trimmed.iter().all(|c| is_ascii_or_arabic_digit(*c)),
        _ => false,
    }
}

fn preceding_abbreviation(chars: &[char], index: usize) -> bool {
    let window_start = index.saturating_sub(12);
    let left: String = chars[window_start..=index].iter().collect();
    for abbreviation in ABBREVIATIONS {
        if !left.ends_with(abbreviation) {
            continue;
        }
        let abbreviation_chars = abbreviation.chars().count();
        let absolute_start = index + 1 - abbreviation_chars;
        if absolute_start == 0 {
            return true;
        }
        let preceding = chars[absolute_start - 1];
        if preceding.is_whitespace() || "([{'\"«،؛:—-".contains(preceding) {
            return true;
        }
    }
    false
}

/// Segment text into sentence spans; ports `dhad.text.sentence_spans`.
pub fn sentence_spans(text: &str) -> Vec<Sentence> {
    if text.is_empty() {
        return Vec::new();
    }
    let chars: Vec<char> = text.chars().collect();
    let length = chars.len();
    let mut out = Vec::new();
    let mut start = 0usize;
    let mut index = 0usize;
    let mut line_content_start = None;
    while index < length {
        let c = chars[index];
        let boundary = if c == '\n' {
            true
        } else if TERMINATORS.contains(&c) {
            if c == '.'
                && (looks_like_decimal(&chars, index)
                    || looks_like_list_marker(&chars, index, line_content_start)
                    || preceding_abbreviation(&chars, index))
            {
                index += 1;
                continue;
            }
            true
        } else {
            false
        };
        if !boundary {
            if line_content_start.is_none() && !c.is_whitespace() {
                line_content_start = Some(index);
            }
            index += 1;
            continue;
        }
        let body_end = index;
        let mut term_end = index + 1;
        while term_end < length && TERMINATORS.contains(&chars[term_end]) {
            term_end += 1;
        }
        while term_end < length && CLOSERS.contains(&chars[term_end]) {
            term_end += 1;
        }
        let chunk: String = chars[start..body_end].iter().collect();
        if !chunk.trim().is_empty() {
            out.push(Sentence {
                text: chunk,
                start,
                end: body_end,
                terminator: chars[body_end..term_end].iter().collect(),
            });
        }
        start = term_end;
        index = term_end;
        if c == '\n' {
            line_content_start = None;
        }
    }
    let tail: String = chars[start..].iter().collect();
    if !tail.trim().is_empty() {
        out.push(Sentence {
            text: tail,
            start,
            end: length,
            terminator: String::new(),
        });
    }
    out
}

#[cfg(test)]
mod complexity_tests {
    use super::{normalize, sentence_spans, tokenize_all, NormalizationMode, TokenKind};
    use std::time::{Duration, Instant};

    #[test]
    fn dot_dense_single_line_segmentation_stays_linear() {
        let text = "word.".repeat(10_000);
        let started = Instant::now();
        let sentences = sentence_spans(&text);
        assert_eq!(sentences.len(), 10_000);
        assert!(started.elapsed() < Duration::from_millis(250));
    }

    #[test]
    fn cumulative_offsets_remain_code_point_accurate() {
        let tokens = tokenize_all("🙂 شَلون؟ A");
        assert_eq!(tokens[0].kind, TokenKind::Symbol);
        assert_eq!((tokens[0].start, tokens[0].end), (0, 1));
        assert_eq!((tokens[2].start, tokens[2].end), (2, 7));
        assert_eq!(tokens[2].text, "شَلون");
    }

    #[test]
    fn aggressive_normalization_collapses_without_trailing_space() {
        assert_eq!(
            normalize("  أَهلاً،   بالعالَم! ", NormalizationMode::Aggressive),
            "اهلا بالعالم"
        );
    }
}
